name: Merge
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-action@v1
      - uses: rekgrpth/git-fetch-upstream-action@v1
        with:
          repository: x-v8/ngx_http_upstream_session_sticky_module
      - uses: rekgrpth/git-merge-upstream-action@v1
      - uses: rekgrpth/git-push-action@v1
